---
name: Code review using CoffeeLint
author: Money Forward, Inc.
description: Analyze code statically using CoffeeLint in Github actions
inputs:
  files:
    description: |
      Specify files or directories

      (Multiple files or directories can be specified by separating them with line feed)
    required: false
  options:
    description: |
      Changes `coffeelint` command line options.

      Specify the options in JSON array format.
      e.g.: '["--ext", ".cjsx"]'
    required: false
  working_directory:
    description: Changes the current working directory of the Node.js process
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'search'
  color: 'orange'
